name: griddler_maker
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  web: ^1.1.1
  image: ^4.2.0         # For image processing (Dart native, works well)
  image_picker: ^1.1.2  # To pick images from gallery or camera
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.6
  lints: ^6.0.0
